// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwoessbpdkvckmiacvso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3b2Vzc2JwZGt2Y2ttaWFjdnNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1NzQ1NjAsImV4cCI6MjA1MzE1MDU2MH0.Gvbae4f31VynTBRbwMbgfwiNvyVsfpvp-N41_bxT0Bg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);